//---------------------------------------------------------------------------

#include <vcl.h>
#pragma hdrstop

#include "Notify.h"
namespace popenable {
#include "popenable.h"	// generated by bmp2rgn
}
namespace popdisable {
#include "popdisable.h"	// generated by bmp2rgn
}
//---------------------------------------------------------------------------
#pragma package(smart_init)
#pragma resource "*.dfm"
TNotifyForm *NotifyForm;
//---------------------------------------------------------------------------
__fastcall TNotifyForm::TNotifyForm(TComponent* Owner)
	: TForm(Owner)
{
	hRgn = NULL;
}
//---------------------------------------------------------------------------
void __fastcall TNotifyForm::FormShow(TObject *Sender)
{
	Setup();
	if (hRgn)
		DeleteObject(hRgn);
	if (enable){
		hRgn = ExtCreateRegion (0,
		sizeof(popenable::bmp2rgn_rgnBytes),
		&popenable::bmp2rgn_rgnData);
	} else {
		hRgn = ExtCreateRegion (0,
		sizeof(popdisable::bmp2rgn_rgnBytes),
		&popdisable::bmp2rgn_rgnData);
	}
	SetWindowRgn( Handle, hRgn, TRUE );
}
//---------------------------------------------------------------------------
void TNotifyForm::Setup()
{
	EnableBmp->Visible = enable;
	DisableBmp->Visible = !enable;
	TImage *bmp = enable ? EnableBmp : DisableBmp;
	Width = bmp->Width;
	Height = bmp->Height;
	bmp->Top = 0;
	bmp->Left = 0;
//	ReleaseCapture();
	SetCapture( Handle );	// captureÇ≈Ç´Ç»Ç¢ÅBÇ»Ç∫ÅH
}
void __fastcall TNotifyForm::FormMouseMove(TObject *Sender,
	  TShiftState Shift, int X, int Y)
{
	ReleaseCapture( );
	Close();
}
//---------------------------------------------------------------------------
void __fastcall TNotifyForm::FormDestroy(TObject *Sender)
{
	DeleteObject( hRgn );	
}
//---------------------------------------------------------------------------


