; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=DokoPop! (Unicode)
AppVerName=DokoPop! 2.1.4
AppPublisher=DokoPop Project
DefaultDirName={pf}\DokoPop! (Unicode)
DefaultGroupName=DokoPop! (Unicode)
DisableProgramGroupPage=yes
InfoBeforeFile=DKPU.TXT
OutputBaseFilename=setup
Compression=lzma
SolidCompression=yes
UninstallDisplayIcon={app}\DKPu.exe

[Languages]
;Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Files]
Source: "DKPu.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "DKPUHK.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "DKPUHK64.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "DKPUHK64.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "amsocr.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "Interop.MODI.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "ExMODIst.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "DKPu.txt"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Tasks]
Name: "startupicon"; Description: "スタートアップにショートカットを作成"; GroupDescription: "スタートアップ"; Flags:

[Icons]
Name: "{group}\DokoPop! (Unicode)"; Filename: "{app}\DKPU.EXE"
Name: "{group}\{cm:UninstallProgram,DokoPop! (Unicode)}"; Filename: "{uninstallexe}"
Name: "{commonstartup}\DokoPop! (Unicode)"; Filename: "{app}\DKPU.EXE"

[Run]
Filename: "{app}\DKPU.EXE"; Description: "{cm:LaunchProgram,DokoPop! (Unicode)}"; Flags: nowait postinstall skipifsilent

