//hk95d.h

#define	DIOC_CHANGE_MEMORY		20
#define	DIOC_QUERY_MEMORY		21
#define	DIOC_WRITEABLE_MEMORY	22
#define	DIOC_NONWRITEABLE_MEMORY 23
#define	DIOC_SET_HOOK			25
#define	DIOC_RESTORE_HOOK		26
#define	DIOC_HOOK_START			30
#define	DIOC_HOOK_END			31
#define	DIOC_LAST_STATUS		32
#define	DIOC_DEBUG				33
